SET NAMES utf8;

CREATE DATABASE IF NOT EXISTS shopdb DEFAULT CHARACTER SET utf8;

CREATE TABLE shopdb.user (
	uid INT UNSIGNED AUTO_INCREMENT,
	uname VARCHAR(255) NOT NULL UNIQUE,
	passwd VARCHAR(50) NOT NULL,
	phone CHAR(11) NOT NULL,
	idcard CHAR(18) NOT NULL,
	PRIMARY KEY (uid)
) ENGINE=INNODB AUTO_INCREMENT=1000 DEFAULT CHARACTER SET utf8;


CREATE TABLE shopdb.commodity_inventory (
	cs INT UNSIGNED AUTO_INCREMENT,
	cid INT(10) NOT NULL,
	cname VARCHAR(255) NOT NULL UNIQUE,
	cprice CHAR(50) NOT NULL,
	cnub CHAR(11) NOT NULL,
	PRIMARY KEY (cs)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARACTER SET utf8;


CREATE TABLE shopdb.sell_info (
	s INT UNSIGNED AUTO_INCREMENT,
	sid INT(15) UNSIGNED ,
	sname VARCHAR(255) NOT NULL UNIQUE,
	sprice INT(10) NOT NULL,
	snub INT(10) NOT NULL,
	ssum INT(15)NOT NULL,
	PRIMARY KEY (s)
) ENGINE=INNODB AUTO_INCREMENT=10 DEFAULT CHARACTER SET utf8;

CREATE TABLE shopdb.us_info (
	us INT UNSIGNED AUTO_INCREMENT,
	usid INT UNSIGNED ,
	usname VARCHAR(255) NOT NULL UNIQUE,
	usprice INT(50) NOT NULL,
	PRIMARY KEY (us)
) ENGINE=INNODB AUTO_INCREMENT=100 DEFAULT CHARACTER SET utf8;

GRANT ALL ON shopdb.* to 'shop'@'127.0.0.1';
FLUSH PRIVILEGES;